#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef HAVE_LIBSM
#undef PACKAGE_LOCALE_DIR
#undef PACKAGE_DATA_DIR
#undef PACKAGE_PLUGIN_DIR
#undef PACKAGE_SOURCE_DIR

#undef HAVE_MADVISE

#undef DEVEL_CODE

#undef HAVE_LIBSNDFILE1
#undef HAVE_OGGVORBIS
#undef OV_READ_FLOAT_THREE_ARGS
#undef HAVE_SPEEX
#undef HAVE_MAD

#undef HAVE_LIBSAMPLERATE

#undef DRIVER_OSS
#undef DRIVER_ALSA
#undef DRIVER_SOLARIS_AUDIO
