.TH SWEEP 1 "21 Apr 2000" Version 0.0
.SH NAME
Sweep - a sound wave editor
.SH SYNOPSIS
.B sweep
[\-h] [\-\-help] [-v] [\-\-version]
[\-\-display \fIdisplay\fP]
[\fIfilename\fP]...

.SH DESCRIPTION
.PP
\fISweep\fP is a sound wave editor.
.SH OPTIONS
.l 
\fISweep\fP accepts the following options:
.TP 8
.B  \-h, \-\-help
Display a list of all commandline options.
.TP 8
.B \-v, \-\-version
Output the version info.
.TP 8
.B \-\-display \fIdisplay\fP
Use the designated X display.

.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
to get the default host and display number.
.TP 8
.B XENVIRONMENT
to get the name of a resource file that overrides the global resources
stored in the RESOURCE_MANAGER property.

.SH SEE ALSO
.BR X (1)
.SH COPYRIGHT
Copyright \(co  2000 Conrad Parker

.SH OTHER INFO

More information is available at http://sweep.sourceforge.net/

.SH AUTHOR
Conrad Parker

