/* Automatically generated by po2tbl.sed from sweep.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Sweep version", 2},
  {"Usage: %s [option ...] [files ...]\n", 3},
  {"Valid options are:\n", 4},
  {"  -h --help                Output this help.\n", 5},
  {"  -v --version             Output version info.\n", 6},
  {"  --display <display>      Use the designated X display.\n", 7},
  {"Sweep", 8},
  {"File", 9},
  {"New", 10},
  {"Open", 11},
  {"Quit", 12},
  {"Help", 13},
  {"About...", 14},
  {"Select", 15},
  {"Select regions of a sample", 16},
  {"\
This tool allows you to select regions of a sample. You can then apply edits \
and effects to the: selected regions. Hold down shift whilst selecting to \
add discontinuous regions to the selection.", 17},
  {"Move", 18},
  {"Move regions in a sample", 19},
  {"With this tool you can move selected regions of a sample.", 20},
  {"Zoom", 21},
  {"Zoom in & out", 22},
  {"\
Zoom in and out of a view. Click anywhere in a view to zoom in on that part \
of the sample. Hold down shift and click on the view to zoom out.", 23},
  {"Open...", 24},
  {"Save", 25},
  {"Save As...", 26},
  {"Revert", 27},
  {"Close", 28},
  {"Edit", 29},
  {"Undo", 30},
  {"Redo", 31},
  {"Delete", 32},
  {"Cut", 33},
  {"Copy", 34},
  {"Paste", 35},
  {"Paste as New", 36},
  {"Clear", 37},
  {"Invert", 38},
  {"All", 39},
  {"None", 40},
  {"View", 41},
  {"Zoom In", 42},
  {"Zoom Out", 43},
  {"Zoom to selection", 44},
  {"Left", 45},
  {"Right", 46},
  {"50%", 47},
  {"100%", 48},
  {"New View", 49},
  {"Sample", 50},
  {"Duplicate", 51},
  {"Filters", 52},
  {"Playback", 53},
  {"Play sample", 54},
  {"Loop sample", 55},
  {"Play selection", 56},
  {"Loop selection", 57},
  {"Note", 58},
  {"Stop", 59},
  {"Untitled", 60},
  {"Mono", 61},
  {"Stereo", 62},
};

int _msg_tbl_length = 62;
