/* Automatically generated by po2tbl.sed from sweep.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Sweep version", 2},
  {"Sweep plugin API version", 3},
  {"Usage: %s [option ...] [files ...]\n", 4},
  {"Valid options are:\n", 5},
  {"  -h --help                Output this help.\n", 6},
  {"  -v --version             Output version info.\n", 7},
  {"  --display <display>      Use the designated X display.\n", 8},
  {"Sweep", 9},
  {"File", 10},
  {"New", 11},
  {"Open", 12},
  {"Quit", 13},
  {"Help", 14},
  {"About...", 15},
  {"Select", 16},
  {"Select regions of a sample", 17},
  {"\
This tool allows you to select regions of a sample. You can then apply edits \
and effects to the: selected regions. Hold down shift whilst selecting to \
add discontinuous regions to the selection.", 18},
  {"Move", 19},
  {"Move regions in a sample", 20},
  {"With this tool you can move selected regions of a sample.", 21},
  {"Zoom", 22},
  {"Zoom in & out", 23},
  {"\
Zoom in and out of a view. Click anywhere in a view to zoom in on that part \
of the sample. Hold down shift and click on the view to zoom out.", 24},
  {"Open...", 25},
  {"Save", 26},
  {"Save As...", 27},
  {"Revert", 28},
  {"Close", 29},
  {"Edit", 30},
  {"Undo", 31},
  {"Redo", 32},
  {"Delete", 33},
  {"Cut", 34},
  {"Copy", 35},
  {"Paste", 36},
  {"Paste as New", 37},
  {"Clear", 38},
  {"Invert", 39},
  {"All", 40},
  {"None", 41},
  {"View", 42},
  {"Zoom In", 43},
  {"Zoom Out", 44},
  {"Zoom to selection", 45},
  {"Left", 46},
  {"Right", 47},
  {"50%", 48},
  {"100%", 49},
  {"New View", 50},
  {"Sample", 51},
  {"Duplicate", 52},
  {"Filters", 53},
  {"Playback", 54},
  {"Play sample", 55},
  {"Loop sample", 56},
  {"Play selection", 57},
  {"Loop selection", 58},
  {"Note", 59},
  {"Stop", 60},
  {"Untitled", 61},
  {"Mono", 62},
  {"Stereo", 63},
};

int _msg_tbl_length = 63;
